# Generated by Django 3.1.3 on 2021-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='money_amount',
            field=models.FloatField(),
        ),
    ]
